version: '3.3'
services:

  ethernode:
    build: ./ethernode
    environment:
      LOG_LEVEL: 3 #0=silent, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=detail
    volumes:
      - ./ethernode/devnet/:/root/devnet
      - ./ethernode/rinkeby/:/root/rinkeby
      - ./data/ethernode/.ethereum:/root/.ethereum
      - ./data/ethernode/.ethash:/root/.ethash
    ports:
      - 127.0.0.1:8545:8545
      #- 127.0.0.1:30303:30303
    entrypoint: echo -e "need use bash to start";
    logging:
      options:
        max-size: 1000m
    restart: "no"

  truffle:
    build: .
    #stdin_open: true
    tty: true
    environment:
      HOST: ethernode
    links:
      - ethernode
    volumes:
      - ./contracts/:/usr/src/app/contracts
      - ./migrations/:/usr/src/app/migrations
      - ./test/:/usr/src/app/test
      - ./truffle.js/:/usr/src/app/truffle.js:ro
      - ./data/truffle/build:/usr/src/app/build
    logging:
      options:
        max-size: 1000m
    restart: "no"